### PR TITLE
[feat] disable-role-endpoint

### PR DESCRIPTION
**Pull request by sparkybug**
​
## Description
Implemented an endpoint to disable roles. This endpoint will allow admins to disable roles that are no longer required within an organization.
​
## Related Issue (https://github.com/hngprojects/hng_boilerplate_nestjs/issues/256)

​
## Motivation and Context

To provide an endpoint for admins to disable any role within their organization, ensuring that only authorized users can perform this action, and maintaining system security.
​
## How Has This Been Tested?
1. Write end-to-end backend unit tests for the full disabling process.
2. Write integration tests for the end-to-end role disabling process.
3. Test all instances for disabling a role (e.g., successful, failed, retry).
​
## Screenshots (if appropriate - Postman, etc):
image

​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Dev-Tonia — APPROVED** [review]

**Comment by devMuhammad05** [comment]
Add the screenshot of the tests also embed the link to the issue

**Comment by sparkybug** [comment]
> Add the screenshot of the tests also embed the link to the issue

Done sir.

Link to issue also below:
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/256

**Comment by sparkybug** [comment]
@Dev-Tonia @tulbadex I have reverted all the migration files I added and re-worked the project. I have also ensured my code passed all the tests both locally and on the PR.

Kindly review.
Thanks.

**Comment by Ruthiejayjay** [comment]
You have over 10 empty files, some have funny names. Please go through your work again

**Comment by sparkybug** [comment]
> You have over 10 empty files, some have funny names. Please go through your work again

Omg!
That is a terrible mistake. I sincerely apologize for that.

I have rectified the issues and made the necessary adjustments.
@Ruthiejayjay

**Review by Ruthiejayjay — APPROVED** [review]

**Pull request merged**
