### PR TITLE
feat: export user data either as json or csv 

### PR DESCRIPTION
**Pull request by Dev-Tonia**
​
## Description
Implement functionality for users to export their data. This feature will allow users to download their personal data in a commonly used format (such as JSON or CSV) directly from the application.

## Related Issue (Link to Github issue)
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/138

​
## Motivation and Context
Provide users with the ability to export their personal data either as json or csv.

​
## How Has This Been Tested?

​
## Screenshots (if appropriate - Postman, etc):
​csv export

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tulbadex** [comment]
I have gone through this pr

**Review by tulbadex — APPROVED** [review]
checked for code changes and naming convention

**Review by timiajayi — APPROVED** [review]
Approved

**Comment by Ruthiejayjay** [comment]
Resolve merge conflicts

**Pull request merged**
