### PR TITLE
[feat] created testimonial update route

### PR DESCRIPTION
**Pull request by olakadasami**
PATCH `api/v1/testimonials/{testimonial_id}`​

## Description

Create a secure API endpoint that permits only authenticated users to modify their testimonial. The endpoint must correctly handle validation errors and return the modified testimonial with the correct status codes.
​
## Related Issue (Link to Github issue)

[Issue 77](https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/77)
​
## Motivation and Context

​This addresses the issue of rectifying an error in the original testimonial or the user revising their feedback due to a shift in their perception of the service.

## How Has This Been Tested?

It has been tested using postman and with automated tests
​
## Screenshots (if appropriate - Postman, etc):
​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Dev-Tonia — COMMENTED** [review]
I thought this endpoint has been worked on before

**Comment by olakadasami** [comment]
> I thought this endpoint has been worked on before

The Create part of it has been worked on
This is the UPDATE route

**Comment by olakadasami** [comment]
> I thought this endpoint has been worked on before

This is the update route.. The GET single testimonial and POST testimonial had been worked on

I believe GET all testimonials and DELETE are still left

**Comment by Dev-Tonia** [comment]
Did you touch the code on the show method.

**Comment by olakadasami** [comment]
> Did you touch the code on the show method.

No. I just did my update method

**Comment by olakadasami** [comment]
> Did you touch the code on the show method.

those shifts maybe due to my formatter in vscode, but I didn't touch that part of the code

**Review by Dev-Tonia — APPROVED** [review]

**Pull request closed without merging**
