### PR TITLE
[FEAT]: Database Setup - Migrations, Models, Seeding #12

### PR DESCRIPTION
**Pull request by onyx093**
#12 
​
## Description

Set up the database for this project using Eloquent as the preferred ORM, and PostgreSQL as the selected DB, but should also be configurable to accommodate other DB flavors. Additionally, ensure a secure database design for users, profile and organizations tables. This setup must follow the migrations, models, and service patterns that are commonly used in Laravel projects.
​
#12 

## Setting Up the Environment

This guide provides step-by-step instructions to help any developer, regardless of their familiarity with Laravel, run the app and test the feature implemented in the PR.

- You should have WSL installed on your windows PC or use a linux distribution(Recommended but not compulsory).
- Have Git installed
- Have PHP 8.1 or higher, PostgreSQL 15 or higher and Composer installed(Mandatory)
- Have Docker installed(Recommended but not compulsory).
- If not using docker, install WAMP, XAMPP or Laragon

## Cloning the repository

```
git clone https://github.com/hngprojects/hng_boilerplate_php_laravel_web.git
cd hng_boilerplate_php_laravel_web
git checkout scaffold
```

### Set Up Environment Variables
Copy the example environment file to create your own `.env` file in the project folder:
    ```
    cp .env.example .env
    ```
Open the `.env` file in a text editor and update the following variables:
    - `DB_CONNECTION` (e.g., `pgsql`)
    - `DB_HOST` (e.g., `127.0.0.1`)
    - `DB_PORT` (e.g., `5432`)
    - `DB_DATABASE` (your database name)
    - `DB_USERNAME` (your database username)
    - `DB_PASSWORD` (your database password)

### Generate Application Key
Run the following command to generate a new application key:
    `sail artisan key:generate` or `php artisan key:generate`

Run the following command to generate a new JWT secret key:
    `sail artisan jwt:secret` or `php artisan jwt:secret `

### Start the Development Server

- Run `composer install`
- Run `sail artisan migrate --seed` to migrate the tables and seed them, in another terminal.
- 
Run the following command to start the Laravel development server:
    `sail artisan up`
The application will be available at http://127.0.0.1/ or http://localhost/.

## Setting up without docker

Move your project folder into the www folder in WAMP, XAMPP or Laragon

### Set Up Environment Variables
Copy the example environment file to create your own `.env` file in the project folder:
    `
    cp .env.example .env
    `
Run the following command to generate a new JWT secret key:
   `php artisan jwt:secret `

Open the `.env` file in a text editor and update the following variables:
    - `DB_CONNECTION` (e.g., `pgsql`)
    - `DB_HOST` (e.g., `pgsgl`)
    - `DB_PORT` (e.g., `5432`)
    - `DB_DATABASE` (your database name)
    - `DB_USERNAME` (your database username)
    - `DB_PASSWORD` (your database password)

### Generate Application Key
Run the following command to generate a new application key:
    `php artisan key:generate`

### Start the Development Server

- Run `composer install`
- Run `php artisan migrate --seed` to migrate the tables and seed them
- 
Run the following command to start the Laravel development server:
    `php artisan serve`
The application will be available at http://127.0.0.1:8000/ or http://localhost/.

## Screenshots:

- [x ] Create users, profiles, organizations, product tables

Here is the migration for the users table
image

Here is the migration for the profiles table
image

Here is the migration for the organisations table
image

Here is the migration for the products table
image

Here is the migration for the organisation_user pivot table
image

- [x ] A user has one profile

From the user model
image

From the profile model
image

- [x ] A user has many products

From the user model
image

From the product model
image

- [ x] A user belongs to many organizations
- [x ] An organization has many users

From the user model
image

From the organisation model
image

**Tables seeding**
- [x ] At least 2 users
- [x ] At least 2 products per user
- [x ] At least 3 organizations
- [x ] User one belongs to 2 of the organizations
- [x ] User 2 belongs to all 3 organizations

image

### You can test the endpoint using Postman

- Open Postman.
- Create a new GET request to http://localhost:8080/api/v1/users/<user_id>, or http://localhost/api/v1/users/<user_id>, if you are using docker.
- Send the request and verify the response.

### Expected Response
```
{
  "name": "John Doe",
  "id": "some-user-id",
  "email": "johndoe@example.com",
  "profile": {
    "first_name": "John",
    "last_name": "Doe",
    "phone": "1234567890",
    "avatar_url": "http://example.com/avatar.jpg"
  },
  "organisations": [
    {
      "org_id": "some-org-id-1",
      "name": "Some Org",
      "description": "Some Org Description"
    },
    {
      "org_id": "some-other-org-id-2",
      "name": "Some Other Org",
      "description": "Some Other Org Description"
    }
  ],
  "products": [
    {
      "product_id": "some-product-id",
      "name": "Some Product",
      "description": "Some Product Description"
    },
    {
      "product_id": "some-other-product-id",
      "name": "Some Other Product",
      "description": "Some Other Product Description"
    }
  ]
}
```
​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by timiajayi** [comment]
PR for [issue](https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/12)

**Comment by nedssoft** [comment]
@onyx093, did you, by any chance, read the post about including now the PR can be tested as part of the PR?

**Comment by onyx093** [comment]
@nedssoft, I have made the necessary changes. Sorry for the oversight.

**Comment by nedssoft** [comment]
@onyx093 I got this error running the seeder 
image

**Comment by nedssoft** [comment]
@onyx093 please include in the fix you're working on to remove the pivot object in the response object. See the screenshot

image

**Review by nedssoft — APPROVED** [review]
For the sake for moving ahead, I'm approving it, will fix the issue separately

**Comment by jovialcore** [comment]
Setting up without docker part....

Will sail command work if you are setting up without docker? Isn't it best to only specify : php artisan jwt:secret

**Comment by jovialcore** [comment]
For clarity, this looks like you wanted to say organizations table and not products ??


Screenshot_20240719-212900

**Comment by onyx093** [comment]
> Setting up without docker part....
> 
> Will sail command work if you are setting up without docker? Isn't it best to only specify : php artisan jwt:secret

Thanks for the correction

**Comment by onyx093** [comment]
> For clarity, this looks like you wanted to say organizations table and not products ??
> 
> Screenshot_20240719-212900

I mistakenly switched it. All corrected now.

**Comment by onyx093** [comment]
Kindly help reopen this pull request so that I can add the required commit to fix other issues @jovialcore @nedssoft

**Comment by jovialcore** [comment]
I reverted it. Now make a new pull request to branch. That should do yeah?

**Comment by onyx093** [comment]
> I reverted it. Now make a new pull request to branch. That should do yeah?

Yeah. Thanks

**Pull request merged**
