### PR TITLE
feat: adding comment functionality and endpoints

### PR DESCRIPTION
**Pull request by yungstarry**
# Add Comment Functionality and Endpoints

## Description

This PR introduces new routes for handling comments on blog posts. The added functionalities include creating, replying, liking, disliking, editing, and deleting comments. The changes ensure that comments are handled effectively,, with proper authentication and authorization checks.

## Related Issue (Link to Github issue)

https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/243
https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/244
https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/245
https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/246
https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/247
https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/248
https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/249

## Motivation and Context

These changes are necessary to provide users with a comprehensive commenting system on blog posts. It enhances user interaction and engagement by allowing users to comment, reply, like, and dislike comments. Additionally, users can edit or delete their comments as needed.

## How Has This Been Tested?

- Created unit tests to cover all new endpoints.
- Manually tested each endpoint using Postman to ensure expected behavior.
- Validated authentication and authorization checks for each endpoint.
- Ran the entire test suite to ensure no existing functionality was broken.
Screenshot (112)

#post man test screenshots below
Screenshot (113)
Screenshot (114)
Screenshot (115)
Screenshot (116)
Screenshot (117)
Screenshot (119)
Screenshot (118)

### Endpoints
- **Create Comment**: `POST /api/v1/blogs/{blogId}/comments`
- **Reply to Comment**: `POST /api/v1/comments/{commentId}/reply`
- **Like Comment**: `POST /api/v1/comments/{commentId}/like`
- **Dislike Comment**: `POST /api/v1/comments/{commentId}/dislike`
- **Edit Comment**: `PATCH /api/v1/comments/edit/{commentId}`
- **Delete Comment**: `DELETE /api/v1/comments/{commentId}`
- **Get Blog Comments**: `GET /api/v1/blogs/{blogId}/comments`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

---

This should provide a comprehensive overview of your changes and how they've been tested, along with a list of the new endpoints.

### CODE REVIEW

**Comment by timiajayi** [comment]
please add postman screenshots

**Comment by devMuhammad05** [comment]
Work on your title, check other approved PR.

**Comment by yungstarry** [comment]
> Work on your title, check other approved PR.

i have changed the title, also i have added the postman test

**Review by timiajayi — APPROVED** [review]
Approved

**Pull request merged**
