### PR TITLE
feat: get and update email templates by admin

### PR DESCRIPTION
**Pull request by abdielwilsn**
​
## Description

An endpoint for admins to retrieve email templates.
​
## Related Issue (Link to Github issue)

​https://github.com/hngprojects/hng_boilerplate_nestjs/issues/234

https://github.com/hngprojects/hng_boilerplate_nestjs/issues/460

## Motivation and Context

To allow admin to retrieve a pagginated list of email templates.
​
## How Has This Been Tested?

​Unit tests and Post man

## Screenshots (if appropriate - Postman, etc):
image

​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by devMuhammad05** [comment]
Edit the title to "feat: get email templates by admin"

**Review by devMuhammad05 — CHANGES_REQUESTED** [review]
Work on the title and move the controller to the admin folder.

**Comment by abdielwilsn** [comment]
> Work on the title and move the controller to the admin folder.

Tests are passing but exiting with a status code of 1 and failing the check. I don't know why

**Comment by abdielwilsn** [comment]
Okay done

**Comment by timiajayi** [comment]
Fix merge conflict add postman  test

**Comment by abdielwilsn** [comment]
> Fix merge conflict add postman test

Done

**Review by timiajayi — APPROVED** [review]
Approved

**Pull request merged**
