### PR TITLE
[feat] delete blog post

### PR DESCRIPTION
**Pull request by kunmifab**
## Description
Created an API endpoint to handle the deletion of a blog. This endpoint validates the blog ID and soft delete on the database upon successful validation.
​
##Endpoint
`[DELETE] /api/v1/blogs/:id`

## Related Issue (Link to Github issue)
​https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/6

An endpoint to permit only super admin to soft-delete a blog post

​
## Motivation and Context
To enable only an authorized user to delete a blog post 
​
## How Has This Been Tested?
- **Successful Deletion of Blog Post** returns status code 202
- **No Blog Post Found** returns status code 404
- **Insufficient Permission** returns status code 403 to indicate unauthorized user
- **Internal Server Error** returns a status code 500 Internal Server Error
- **Invalid Id Parameters** returns a status code 400 for Bad Request
Feature tests:
All test cases passed.
​
## Screenshots (if appropriate - Postman, etc):
image
​

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by Dev-Tonia — COMMENTED** [review]
Revert contributors_guide file back  to how it was.
Reaname your PR

**Comment by kunmifab** [comment]
> Revert contributors_guide file back to how it was. Reaname your PR

done

**Review by timiajayi — APPROVED** [review]
looks okay

**Review by tulbadex — APPROVED** [review]
approved

**Pull request merged**
