### PR TITLE
[FEAT] Create New Job Listing 

### PR DESCRIPTION
**Pull request by AsciencioAlex**
## Description
Implement an API endpoint to create a new job listing in the database. This endpoint allows authenticated users to submit job details and store them in the system. Upon successful creation, it returns the newly created job listing details with a `201` status. If an error occurs, an appropriate error status will be returned.

## Related Issue
- [Backend Issue](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/159)

## Endpoints
`POST /api/v1/jobs`

## Motivation and Context
Enable users to create job listings and store them in the database for later retrieval and display.

## How Has This Been Tested?
- The endpoint is accessible at `POST /api/v1/jobs`.
- The endpoint accepts HTTP POST requests.
- The endpoint checks that the user has the appropriate permissions.
- The endpoint validates all data passed in the body of the request.
- Checks if the requests to the endpoint include a valid authentication token in the Authorization header (`Authorization: Bearer <token>`).
- Given a request with valid job details, when the user is authenticated and authorized, the system creates the job listing with a status code of 201.
- Given a request with invalid request data, the system returns a 400 Bad Request status.
- Given a request without authentication, the system returns a 401 Unauthenticated status.
- Unit tests:
  - All test cases passed.
  - Successful response with valid data.
  - Invalid request data.
  - Missing required fields.
  - Appropriate status codes.

## Screenshots (if appropriate)
postman_test

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by timiajayi** [comment]
Fix merge conflict

**Comment by AsciencioAlex** [comment]
Merge conflict fixed

**Comment by timiajayi** [comment]
Fix title na, and you didn’t add [feat] 
Checklist isn’t filled well

**Comment by AsciencioAlex** [comment]
@buka4rill I have made the changes. Kindly re-open the PR

**Pull request closed without merging**
