### PR TITLE
feat: fetch a role in an organisation endpoint

### PR DESCRIPTION
**Pull request by sparkybug**
## Description

Develop an API endpoint to fetch a specific role within an organisation.
​
## Related Issue (Link to Github issue)

https://github.com/hngprojects/hng_boilerplate_php_laravel_web/issues/418
​
## Motivation and Context

Enable users to fetch a specific role within an organisation.
​
## How Has This Been Tested?

Unit Tests:
- [x] Successful response with valid organisation ID and role ID.
- [x] Invalid organisation ID format.
- [x] Invalid role ID format.
- [x] Non-existent organisation ID.
- [x] Non-existent role ID.
- [x] Internal server error.
​
## Screenshots (if appropriate - Postman, etc):
image
image

​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by timiajayi — APPROVED** [review]

**Comment by timiajayi** [comment]
need additional approval

**Comment by sparkybug** [comment]
@Dev-Tonia

**Comment by sparkybug** [comment]
> need additional approval

@Dev-Tonia please help approve this. God bless you!

**Review by Dev-Tonia — APPROVED** [review]

**Comment by timiajayi** [comment]
failing test

**Comment by timiajayi** [comment]
Merge conflict

**Comment by timiajayi** [comment]
Merge conflict

**Comment by sparkybug** [comment]
> Merge conflict

I have fixed this boss.

**Pull request merged**
