### PR TITLE
[feat] user-deactivation-endpoint

### PR DESCRIPTION
**Pull request by sparkybug**
​
## Description
This endpoint allows an authenticated user to deactivate their account.
​
## Related Issue (https://github.com/hngprojects/hng_boilerplate_nestjs/issues/65)

​
## Motivation and Context
The purpose of the user deactivation endpoint is to allow users to deactivate their accounts, enhancing user control and data privacy.
​
## How Has This Been Tested?
Test 200 status code and success message for successful deactivation
Test missing or invalid confirmation field
Test email is sent to the user upon deactivation
Test the full flow of the deactivation process.
​
## Screenshots (if appropriate - Postman, etc):
​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by Dev-Tonia — APPROVED** [review]

**Review by bhimbho — CHANGES_REQUESTED** [review]
look into soft deletes for user model, this will add deleted_at to user schema. having deactivation_reason is fine though
There is also alot of commented code. remove them.
There is already a roles and permission migration not sure why you need roles again

**Review by tulbadex — CHANGES_REQUESTED** [review]
This two fields can't be added to existing migration
```bash
$table->boolean('is_active')->default(true);
$table->boolean('is_default')->default(false);
```
move it to a new migration by adding to the existing table

**Comment by sparkybug** [comment]
> This two fields can't be added to existing migration
> 
> ```shell
> $table->boolean('is_active')->default(true);
> $table->boolean('is_default')->default(false);
> ```
> 
> move it to a new migration by adding to the existing table

but I did that already by creating the migration files "add_status_to_users_table".
same goes for the "add_is_admin_to_roles_table"

Please, could you be more specific boss?
Thanks so much.

**Comment by sparkybug** [comment]
@tulbadex @bhimbho @Dev-Tonia I have reverted all the migration files I added and re-worked the project. I have also ensured my code passed all the tests both locally and on the PR.

Kindly review.
Thanks.

**Pull request merged**
