### PR TITLE
[FEAT]: Product Categories Listing API Endpoint

### PR DESCRIPTION
**Pull request by sam-sny**
## **Description**
Create an API endpoint to retrieve all product categories, providing essential information for product navigation and filtering.
### **Motivation and Context**
- This changes ensures that the API endpoint for retrieving product categories.
- This changes Implements efficient database querying to fetch category data.
- This changes Includes proper indexing on the categories table for optimal performance.
- This changes ensures proper error handling for invalid requests or server-side issues.
## **Testing**
This code was tested using **Postman**
## **Product Categories Listing [GET] /api/v1/products/categories**

**Successful Request and Response** 

Screenshot (546)

**Invalid Request and Error Response**

- Invalid Query Parameter
Screenshot (547)

## **Types of changes**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## **Checklist:**
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Ruthiejayjay** [comment]
This branch has merge conflicts

**Comment by sam-sny** [comment]
The conflict has been resolved

**Comment by Ruthiejayjay** [comment]
It's not linked to an issue

**Comment by sam-sny** [comment]
I have linked it to it's appropriate issue

**Pull request merged**
